valadoc --directory=docs \
    --package-name=ZeroG \
    --vapidir=lib/vapis \
    --pkg=lua \
    --pkg=mt19937ar \
    --pkg=posix \
    --pkg=SDL2_image \
    --pkg=SDL2_mixer \
    --pkg=SDL2_ttf \
    --pkg=gio-2.0 \
    --pkg=sdl2 \
    lib/components.vala \
    lib/entity.vala \
    lib/entitas/Group.vala \
    lib/entitas/Matcher.vala \
    lib/entitas/World.vala \
    lib/entitas/entitas.vala \
    lib/entitas/events/ComponentReplaced.vala \
    lib/entitas/events/EntityChanged.vala \
    lib/entitas/events/EntityReleased.vala \
    lib/entitas/events/GroupChanged.vala \
    lib/entitas/events/GroupUpdated.vala \
    lib/entitas/events/GroupsChanged.vala \
    lib/entitas/events/WorldChanged.vala \
    lib/goop/Class.vala \
    lib/goop/Guid.vala\
    lib/sdx/ApplicationListener.vala \
    lib/sdx/Color.vala \
    lib/sdx/Files.vala \
    lib/sdx/Font.vala \
    lib/sdx/InputMultiplexer.vala \
    lib/sdx/InputProcessor.vala \
    lib/sdx/Screen.vala \
    lib/sdx/audio/Sound.vala \
    lib/sdx/audio/audio.vala \
    lib/sdx/exceptions.vala \
    lib/sdx/files/FileHandle.vala \
    lib/sdx/files/files.vala \
    lib/sdx/graphics/BitmapFont.vala \
    lib/sdx/graphics/Camera.vala \
    lib/sdx/graphics/NinePatch.vala \
    lib/sdx/graphics/Sprite.vala \
    lib/sdx/graphics/Surface.vala \
    lib/sdx/graphics/TextureAtlas.vala \
    lib/sdx/graphics/TextureEnums.vala \
    lib/sdx/graphics/TextureRegion.vala \
    lib/sdx/graphics/graphics.vala \
    lib/sdx/math/Interpolation.vala \
    lib/sdx/math/Timeline.vala \
    lib/sdx/math/Tween.vala \
    lib/sdx/math/TweenAccessor.vala \
    lib/sdx/math/TweenManager.vala \
    lib/sdx/math/Tweenbase.vala \
    lib/sdx/math/Vector2.vala \
    lib/sdx/sdx.vala \
    lib/sdx/ui/Button.vala \
    lib/sdx/ui/Component.vala \
    lib/sdx/ui/Label.vala \
    lib/sdx/utils/Cache.vala \
    lib/sdx/utils/File.vala \
    lib/sdx/utils/Json.vala \
    lib/sdx/utils/StringTokenizer.vala \
    lib/sdx/utils/utils.vala 