/**
 * Entitas Generated Entity & Components for shmupwarz
 *
 * do not edit this file
 */
namespace Entitas 
{
	public struct Entity 
	{			   	
											/* Core component: */  
		public int 			id;				/* sequentially assigned id# */
		public string 		name; 			/* display name */
		public int 			pool;			/* pool entities by type */
		public uint64 		mask;			/* HasComponent bit array */
		public Transform 	transform;		/* core game object */

        /**
         * Subscribe to Component Added Event
         * type Event.EntityChanged 
		 */
		public Event.EntityChanged		onComponentAdded;

        /**
         * Subscribe to Component Removed Event
         * type Event.EntityChanged 
		 */
		public Event.EntityChanged		onComponentRemoved;

        /**
         * Subscribe to Entity Released Event
         * type Event.EntityReleased 
		 */
		public Event.EntityReleased		onEntityReleased;

        /**
         * Subscribe to Component Replaced Event
         * type Event.ComponentReplaced 
		 */
		public Event.ComponentReplaced	onComponentReplaced;

		/* ============================ */
		public Layer? 		layer;			/* value */
		public Show?		show;			/* flag */
		public Tint? 		tint;			/* value */
		public Velocity? 	velocity;		/* value */
		/* ============================ */

		public Entity(int id, 
			Event.OnEntityChanged? ComponentAddedOrRemoved = null, 
			Event.OnEntityReleased? ComponentEntityReleased = null, 
			Event.OnComponentReplaced? ComponentComponentReplaced = null)
		{

			this.id = id;

            onEntityReleased = new Event.EntityReleased();
            onComponentAdded = new Event.EntityChanged();
            onComponentRemoved = new Event.EntityChanged();
            onComponentReplaced = new Event.ComponentReplaced();

			if (ComponentEntityReleased != null)
				onEntityReleased.Add(ComponentEntityReleased);
			if (ComponentAddedOrRemoved != null)
				onComponentAdded.Add(ComponentAddedOrRemoved);
			if (ComponentAddedOrRemoved != null)
				onComponentRemoved.Add(ComponentAddedOrRemoved);
			if (ComponentComponentReplaced != null)
				onComponentReplaced.Add(ComponentComponentReplaced);
		}

        /**
         * Destroy
         *
         */
		public void Destroy() 
		{
			SetActive(false);
		}

        /**
         * HasAnyComponent
         *
         * @param Array<number> indices
         * @return boolean
         */
		public bool HasAnyComponent(int[] indices) 
		{
			foreach (var index in indices)
				if ((POW2[index] & mask) != 0) return true;
			return false;
		}

         /**
          * HasComponent
          *
          * @param number index
          * @return boolean
          */
		public bool HasComponent(int index) 
		{
			return (POW2[index] & mask) != 0;
		}

        /**
         * HasComponents
         *
         * @param Array<number> indices
         * @return boolean
         */
		public bool HasComponents(int[] indices) 
		{
			foreach (var index in indices) 
				if ((POW2[index] & mask) == 0) return false;
			return true;
		}

		public bool IsActive() 
		{
			return (mask & ACTIVE) == ACTIVE;
		}

		public Entity* SetId(int id) 
		{
			this.id = id;
			return &this;
		}

		public Entity* SetName(string name) 
		{
			this.name = name;
			return &this;
		}

		public Entity* SetActive(bool active) 
		{
			if (((mask & ACTIVE) == ACTIVE ) == active) return &this;
			if (active) mask |= ACTIVE;
			else mask ^= ACTIVE;
			return &this;
		}

		public Entity* SetBounds(int x, int y, int w, int h) 
		{
			transform.aabb.x = x;
			transform.aabb.y = y;
			transform.aabb.w = w;
			transform.aabb.h = h;
			return &this;
		}

		public Entity* SetPool(int pool) 
		{
			this.pool = pool;
			return &this;
		}

		public Entity* SetPosition(float x, float y) 
		{
			transform.position.x = x;
			transform.position.y = y;

			if (transform.sprite.centered) 
			{
				transform.aabb.x = (int)(x - transform.aabb.w / 2);
				transform.aabb.y = (int)(y - transform.aabb.h / 2);
			} 
			else 
			{
				transform.aabb.x = (int)x;
				transform.aabb.y = (int)y;
			}
			return &this;
		}

		public Entity* SetScale(float x, float y) 
		{
			transform.scale.x = x;
			transform.scale.y = y;
			return &this;
		}

		public Entity* SetTransform(Sdx.Graphics.Sprite sprite) 
		{
			transform = Transform(sprite);
			return &this;
		}
		
		public string ToString() 
		{
			var sb = new StringBuilder();
			sb.Append(id.ToString())
			.Append("(")
			.Append(name)
			.Append(")");

			for (var i = 1, seperator = false; i <= ComponentString.length; i++) 
			{
				if (HasComponent(i)) 
				{
					if (seperator) sb.Append(", ");
					sb.Append(ComponentString[i]);
					seperator = true;
				}
			}
			return sb.str;
		}


		public bool HasLayer() {
			return (mask & LAYER) == LAYER;
		}

		public Entity* AddLayer(int value) { 
			if ((mask & LAYER) == LAYER) throw new Exception.EntityAlreadyHasComponent("Layer");
			layer = { value };
			mask |= LAYER;
			onComponentAdded.Dispatch(&this, Components.LayerComponent, &layer);
			return &this;
		}

		public Entity* SetLayer(int value) {
			if ((mask & LAYER) != LAYER) throw new Exception.EntityDoesNotHaveComponent("Layer");
			this.layer.value = value;
			return &this;
		}

		public Entity* RemoveLayer() {
			if ((mask & LAYER) != LAYER) throw new Exception.EntityDoesNotHaveComponent("Layer");
			var prev = layer;
			layer = null;
			mask ^= LAYER;
			onComponentRemoved.Dispatch(&this, Components.LayerComponent, &prev);
			return &this;
		}

		public Entity* SetShow(bool value) {
			if (value) {
				show = { true };
				mask |= SHOW;
				onComponentAdded.Dispatch(&this, Components.ShowComponent, &show);
			} else {
				var prev = show;
				show = null;
				mask ^= SHOW;
				onComponentRemoved.Dispatch(&this, Components.ShowComponent, &prev);
			}
			return &this;
		}

		public bool IsShow() {
			return (mask & SHOW) == SHOW;
		}


		public bool HasTint() {
			return (mask & TINT) == TINT;
		}

		public Entity* AddTint(int r, int g, int b, int a) {
			if ((mask & TINT) == TINT) throw new Exception.EntityAlreadyHasComponent("Tint");
			tint = { r, g, b, a };
			mask |= TINT;
			onComponentAdded.Dispatch(&this, Components.TintComponent, &tint);
			return &this;
		}

		public Entity* SetTint(int r, int g, int b, int a) {
			if ((mask & TINT) != TINT) throw new Exception.EntityDoesNotHaveComponent("Tint");
			this.tint.r = r;
			this.tint.g = g;
			this.tint.b = b;
			this.tint.a = a;
			return &this;
		}

		public Entity* RemoveTint() {
			if ((mask & TINT)!= TINT) throw new Exception.EntityDoesNotHaveComponent("Tint");
			var prev = tint;
			tint = null;
			mask ^= TINT;
			onComponentRemoved.Dispatch(&this, Components.TintComponent, &prev);
			return &this;
		}

		public bool HasVelocity() {
			return (mask & VELOCITY) == VELOCITY;
		}

		public Entity* AddVelocity(float x, float y) { 
			if ((mask & VELOCITY) == VELOCITY) throw new Exception.EntityAlreadyHasComponent("Velocity");
			velocity = { x, y };
			mask |= VELOCITY;
			onComponentAdded.Dispatch(&this, Components.VelocityComponent, &velocity);
			return &this;
		}

		public Entity* SetVelocity(float x, float y) {
			if ((mask & VELOCITY) != VELOCITY) throw new Exception.EntityDoesNotHaveComponent("Velocity");
			this.velocity.x = x;
			this.velocity.y = y;
			return &this;
		}

		public Entity* RemoveVelocity() {
			if ((mask & VELOCITY) != VELOCITY) throw new Exception.EntityDoesNotHaveComponent("Velocity");
			var prev = velocity;
			velocity = null;
			mask ^= VELOCITY;
			onComponentRemoved.Dispatch(&this, Components.VelocityComponent, &prev);
			return &this;
		}
	}
}
